### ISSUE TITLE
new argument; -t 'this is ++mark and Selected text'

### ISSUE THREAD

**Issue by linuxcaffe** [nocejo/trev#19]
One might review tasks with a given filter and ++mark for various reason, and this feature requests seeks to make that reason clear. for example;

    $ trev.py ++next -t 'These tasks should be done next. (use "+" or "-" to add or remove next tag)'

and then the first line after the graph reads;

     Selected (+next): These tasks should be done next. (use "+" or "-" to add or remove next tag)

allowing more complex, multi-step review scripts to explain the intent of each step.

**Comment by linuxcaffe** [comment]
TL;DR
-t 'This text gets appended to upper label line'
-T 'This text gets appended to lower label line'

**Comment by nocejo** [comment]
Just commited an implementation:

- trev -T /additional text/ : add text to upper label.
- trev -t /additional text/ : add text to lower label.

- '' and "" not valid delimiters due to shell escape.

I used /Make these calls/ , but other delimiters can be considered.

- Some characters need escaping: -T /Make these phone calls\!/

**Comment by nocejo** [comment]
No way to include '\n' into the argument.

**Comment by nocejo** [comment]
As the command line order seemed unusual I've just commited a modification to issue options first and arguments later. Documentation is updated.

**Comment by nocejo** [comment]
Issues #19 (new argument; -t 'this is ++mark and Selected text'), #22 (new argument; -f ~/.task/review/weekly.review[.txt]) and #23 (.rc option: info_view=on/off) give rise to the convenience of having a .trevrc file containing switches, default values and 'review modes'.

Specific review modes (as the active tasks, next actions,overdue tasks, marked for weekly review... proposed) can mimic the report mechanism in taskwarrior; i.e.: as the content:

    report.minimal.columns    = id,description.count,tags.count,project
    report.minimal.filter     = (status:pending or status:waiting)
    report.minimal.labels     = ID,Description,Tags,Project
    report.minimal.sort       = due-,project+/

defines the 'minimal' report in taskwarrior's ~/.taskrc file, some text like:

    review.mode.calls.filter     = due.before:tomorrow

    review.mode.calls.seltag     = +call

    review.mode.calls.acton      = mod +call

    review.mode.calls.actoff     = mod -call

    review.mode.calls.prompt     = 'trev calls> ' # quotes to remark blank

    review.mode.calls.lblstyle   = reverse bold

    review.mode.calls.sepstyle   = underline bold

    review.mode.calls.upaddtext  = Make these phone calls!

    review.mode.calls.loaddtext  = These are high-urgency actionable tasks!


can define the 'calls' mode in some .trevrc file.

**Comment by nocejo** [comment]
Please, read 'urgency.over:12 +READY' instead of 'due.before:tomorrow'

**Comment by nocejo** [comment]
Old issue.
