### ISSUE TITLE
new argument; -f ~/.task/review/weekly.review[.txt]

### ISSUE THREAD

**Issue by linuxcaffe** [nocejo/trev#22]
For more complex, multi-step reviews, the -f /pathto/file.review[.txt] argument causes trev to take its arguments line-by-line from the target file. This will allow users to maintain several review-files, fully commented and of any complexity, and to start the process with a simple "trev.py -f something.review".

**Comment by linuxcaffe** [comment]
here's an example (with liberal use of issue #22)
{noformat}
#This is an example of a trev review file, invoked with 'trev -f weekly review'

#Each line is like a trev command, invoked one after another, first to last.

#overdue tasks
++next -t 'These tasks are "next"'' -T 'These tasks are overdue \n (use "+" or "-" to add or remove +next tag)' +OVERDUE

#due tasks
++next -t 'These tasks are "next"'' -T 'These tasks are due \n (use "+" or "-" to add or remove +next tag)' +DUE

#blocking 
++next -t 'These tasks are "next"'' -T 'These tasks are blocking other tasks \n (use "+" or "-" to add or remove +next tag)' +BLOCKING

#high priority
++next -t 'These tasks are "next"'' -T 'These tasks are marked as high-priority \n (use "+" or "-" to add or remove +next tag)' priority:H

#no project
++next -t 'These tasks are "next"'' -T 'These tasks have no project assigned \n (use "+" or "-" to add or remove +next tag)' project.any:

#waiting
++next -t 'These tasks are "next"'' -T 'These tasks are waiting (hidden until wait:date) \n (use "+" or "-" to add or remove +next tag)' +WAITING
{noformat}

**Comment by linuxcaffe** [comment]
A more comprehensive approach to a multi-step review file, might take into account other configuration options;
<pre>
# active tasks
set seltag = active    	# selection tag (fake, active is a report, not a tag)
set on     = start     	# select action
set off    = stop      	# unselect action
set upper  = These tasks are active
set lower  = Use "+" to start, and "-" to stop a task
set filter =
review

# next actions
set seltag = +next      
set on     = mod +next  
set off    = mod -next  
set upper  = These tasks are marked as Next Actions 
set lower  = Use "+" to add, and "-" to remove +next tag
set filter = +next
review

# overdue tasks
set seltag = +OVERDUE -DUE       
set on     = start
set off    = stop
set upper  = These tasks are overdue
set lower  = Use "+" to start, and "-" to stop a task
set filter = +OVERDUE -DUE
review
 
# marked for weekly review
set seltag = +w        
set on     = mod +w    	
set off    = mod -w 
set upper  = These tasks are marked for weekly review
set lower  = Use "+" to add, and "-" to remove +w tag
set filter = +w
review
 
# tasks due "someday"
set seltag = +someday     
set on     = mod +someday 
set off    = mod -someday 
set upper  = These tasks are marked as "someday" (due 1/18/2038)
set lower  = Use "+" to add, and "-" to remove +someday tag
set filter = +someday
review
</pre>

**Comment by nocejo** [comment]
Issues #19 (new argument; -t 'this is ++mark and Selected text'), #22 (new argument; -f ~/.task/review/weekly.review[.txt]) and #23 (.rc option: info_view=on/off) give rise to the convenience of having a .trevrc file containing switches, default values and 'review modes'.

Specific review modes (as the active tasks, next actions,overdue tasks, marked for weekly review... proposed) can mimic the report mechanism in taskwarrior; i.e.: as the content:

    report.minimal.columns    = id,description.count,tags.count,project
    report.minimal.filter     = (status:pending or status:waiting)
    report.minimal.labels     = ID,Description,Tags,Project
    report.minimal.sort       = due-,project+/

defines the 'minimal' report in taskwarrior's ~/.taskrc file, some text like:

    review.mode.calls.filter     = due.before:tomorrow

    review.mode.calls.seltag     = +call

    review.mode.calls.acton      = mod +call

    review.mode.calls.actoff     = mod -call

    review.mode.calls.prompt     = 'trev calls> ' # quotes to remark blank

    review.mode.calls.lblstyle   = reverse bold

    review.mode.calls.sepstyle   = underline bold

    review.mode.calls.upaddtext  = Make these phone calls!

    review.mode.calls.loaddtext  = These are high-urgency actionable tasks!


can define the 'calls' mode in some .trevrc file.

**Comment by nocejo** [comment]
Please, read 'urgency.over:12 +READY' instead of 'due.before:tomorrow'

**Comment by nocejo** [comment]
This is already implemented in rc file. Old issue.
