### ISSUE TITLE
.rc option: info_view=on/off

### ISSUE THREAD

**Issue by linuxcaffe** [nocejo/trev#23]
info_view=on

When set to "on", this option causes trev to use the info report for all queries.
In the "off" position, trev uses the default.command. 
related to #18

**Comment by nocejo** [comment]
Issues #19 (new argument; -t 'this is ++mark and Selected text'), #22 (new argument; -f ~/.task/review/weekly.review[.txt]) and #23 (.rc option: info_view=on/off) give rise to the convenience of having a .trevrc file containing switches, default values and 'review modes'.

Specific review modes (as the active tasks, next actions,overdue tasks, marked for weekly review... proposed) can mimic the report mechanism in taskwarrior; i.e.: as the content:

    report.minimal.columns    = id,description.count,tags.count,project
    report.minimal.filter     = (status:pending or status:waiting)
    report.minimal.labels     = ID,Description,Tags,Project
    report.minimal.sort       = due-,project+/

defines the 'minimal' report in taskwarrior's ~/.taskrc file, some text like:

    review.mode.calls.filter     = due.before:tomorrow

    review.mode.calls.seltag     = +call

    review.mode.calls.acton      = mod +call

    review.mode.calls.actoff     = mod -call

    review.mode.calls.prompt     = 'trev calls> ' # quotes to remark blank

    review.mode.calls.lblstyle   = reverse bold

    review.mode.calls.sepstyle   = underline bold

    review.mode.calls.upaddtext  = Make these phone calls!

    review.mode.calls.loaddtext  = These are high-urgency actionable tasks!


can define the 'calls' mode in some .trevrc file.

**Comment by nocejo** [comment]
Please, read 'urgency.over:12 +READY' instead of 'due.before:tomorrow'
