### ISSUE TITLE
bug: trev.pl only displays the first (8 or 9?) tasks

### ISSUE THREAD

**Issue by linuxcaffe** [nocejo/trev#27]
With no other options or arguments, I imagine trev should show all tasks, 
but it's not, only listing the first 8 or 9

**Comment by nocejo** [comment]
Is this a recent issue? 
In that case, must be due to the one of the last 6 commits.

**Comment by linuxcaffe** [comment]
no, I don't think it's recent. Is this not reproduced on your system?

**Comment by nocejo** [comment]
No, I can't reproduce it. I've been trying, reviewed more than 300 tasks, projects, starting at a different task id... and everything's fine. Ubuntu 14.04 and Debian stable here.

**Comment by linuxcaffe** [comment]
my fault entirely, bad invocation!
