### ISSUE TITLE
new command: rev[iew] [name]

### ISSUE THREAD

**Issue by linuxcaffe** [nocejo/trev#33]
In order to initiate a specific review mode, as configured in the rc, a new command "review" could be used, and it should match partial review names.

Without the rev[iew] command, trev should execute the review.default.

Partial name matching will allow more complex, or "orthogonal" review.
consider example rc configs;
<pre>
review.required-project
...
review.required-priority
...
review.old-project
...
review.old-tag
</pre>
with command 
<pre>
trev.pl rev req
</pre>
both of the "required" reviews would be run (in the order found in the rc), but with
<pre>
trev.pl rev proj
</pre>
both 'review.required-project' and 'review.old-project' would be run.

**Comment by nocejo** [comment]
Wouldn't be easier to ask simply for 
<pre>trev required</pre>
and let `trev` locate, configure and run --sequentially-- every mode starting by `required-`
<pre>
review.required-project.seltag  = ...
review.required-project.filter  = ...
...
review.required-priority.seltag = ...
review.required-priority.filter = ...
review.required-priority.lower  = ...
...
</pre>
that it finds in the `trevrc` file?  Perhaps I'm misunderstanding the concept.

**Comment by linuxcaffe** [comment]
no, it's me misunderstanding!
If you can use the review-name as the first argument, then there's no need for command "trev.pl review"

The salient part of the issue, is the partial match, ignore the "new command" part.

**Comment by nocejo** [comment]
Fine. I'll try it when trevrc is done.

**Comment by linuxcaffe** [comment]
non-issue

**Comment by nocejo** [comment]
What's the meaning of 'non-issue'?

**Comment by linuxcaffe** [comment]
it means it's an issue that never should have been filed :)
