### ISSUE TITLE
Update documentation following rc file introduction 

### ISSUE THREAD

**Issue by nocejo** [nocejo/trev#34]
A Warning has been issued in the doc, but a complete revision must be performed.
In my advice is better to wait until planned changes concerning multi-step review (issue #35) take place, because these will affect behavior concerning the rc file.

**Comment by nocejo** [comment]
I'm thinking in shifting from pod and markdown doc to man pages, one for `trev` and other for `trevrc`.
Some opinion? 
What would be of more utility?
(In particular, of more utility for a future development in the realm of `tasksh`)

**Comment by linuxcaffe** [comment]
markdown +1

**Comment by nocejo** [comment]
OK: markdown +2 (mine too) , rest-of-yhe-world 0. Go markdown.

**Comment by nocejo** [comment]
I'm using the term *named review* instead of *review mode* . Think this is more pertinent for the concept.

**Comment by nocejo** [comment]
I think it's done.
